config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Create the home and about routes
  root 'pages#home'
  get 'about', to: 'pages#about'
  # create only the individual routes one by one
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/article.rb
# define article model as class, inherits from ApplicationRecord
class Article < ApplicationRecord
    # create association between Articles and a User

    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    # ensures the title is present for any article to be saved
    # enforcing minimum data lengths for the title and the description
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/articles_controller.rb
#ArticlesController inherits from ApplicationController
class ArticlesController < ApplicationController
  before_action :set_article, only:[:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

    def show
        #Assign an item from the Article table to a variable
        #params are the parameters passed in, and can be accessed by
        #[:param_name]

        #accessing article id tp show on page

        #'@' converts a variable to an instance variable
        # @article = Article.find(params[:id])
    end
    def index
        # show all
        # @articles = Article.all

        # add pagination
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    def new
        # creat article instance variable for use with new submissions
        @article = Article.new
    end

    def edit
        # find the article based on the ID from the params hash
        # @article = Article.find(params[:id])
    end

    def create
        # create new article with instance variable
        # values need to be whitelisted to be allowed
        # to post
        # @article = Article.new(params.require(:article).permit(:title, :description))
        
        @article = Article.new(article_params_whitelist)
        # assign the user who created the article to the currently logged in user
        # see the application controller helper methods
        @article.user = current_user
        
        # save the article
        if @article.save
          flash[:notice] = "Article was created successfully"
        
        # flash[:alert] = "Something went wrong"
        # redirect to the page of the article
        #redirect_to article_path(@article)
          redirect_to @article
        else
          render 'new'
        end
    end

    #Update definition
    def update
        # find the specific article to update by ID
        # @article = Article.find(params[:id])
        # if the update was successful
        # if @article.update(params.require(:article).permit(:title, :description))

        if @article.update(article_params_whitelist)
            # display msg on screen
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        # if the update was not successful, show the edit screen again
        else
            render 'edit'
        end
    end
    # destroy route
    def destroy
      # @article = Article.find(params[:id])
      @article.destroy
      redirect_to articles_path
    end

    # This private is NOT a code block.  Anything following it is simply a private method
    # or function
    private 

    # for refactoring.  Run before any action to grab the article ID for specific actions
    def set_article
      @article = Article.find(params[:id])
    end
    # for refactoring
    # returns the whitelisted params for use in the create and update actions
    def article_params_whitelist
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article!"
        redirect_to @article
    end
  end
end 

app/views/articles/_article.html.erb
<div class="container">
<%#  loop through each article %>
  <% obj.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to article.user.username, user_path(article.user) %>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-danger" %></h5>
            <%# truncate method to truncate article description lengths %>
            <p class="card-text"><%= truncate(article.description, length: 100)%></p>
            <% if article.categories.any? %>
              <p>Categories: <%= render article.categories%><br>
            <% end %>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%# Render the form partial for errors, pass in the contextual @article variable %>
      <%= render 'shared/errors', obj: @article %>
      <%# Change form scope to show current information to be edited %>
      <%= form_with(model:@article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :category, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list below (can be empty)"}, { multiple: true, size: 3, class: "custom-select shadow rounded" } ) %>
          </div>
        </div>

        <div class="form-group-row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
      <div class="mb-3">
      <%= link_to "[ Return to Articles listing ]", articles_path, class: "text-info" %>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="mt-4">Articles Listing Page</h1>

<%# If there were any errors with posting the article, display
to the end user in an unordered list %>
<%= render 'form'%>

app/views/articles/index.html.erb
<h1 class="mt-4">Articles Listing Page</h1>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>
<%= render 'article', obj: @articles %>
<%= button_to "Create new Article",new_article_path, method: :get %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="mt-4">Create New Article</h1>

<%# If there were any errors with posting the article, display
to the end user in an unordered list %>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="mt-4"><%= @article.title%></h2>
<div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= @article.user.username %>
            <%= link_to gravatar_for(@article.user, size: 50), user_path(@article.user) %>
          </div>
          <div class="card-body">
            <%# truncate method to truncate article description lengths %>
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
            <% if @article.categories.any? %>
              <p>Categories: <%= render @article.categories %></p>
            <% end %>
            <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
              <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
              <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-outline-danger" %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago,
            Edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
</div>
<p><%= button_to "Create new Article",new_article_path, method: :get %>
<%= link_to "Return to Articles listing", articles_path %>
</p>