config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Create the home and about routes
  root 'pages#home'
  get 'about', to: 'pages#about'
  # create only the individual routes one by one
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]
    def new
        @category = Category.new
    end
    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:success] = "Category name was updated successfully"
            redirect_to category_path(@category)
        else
            render 'edit'
        end
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 3)
        # @categories = Category.all
    end
    def show
        @category = Category.find(params[:id])
        @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end
    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end

end

app/views/categories/_category.html.erb
<span class="badge badge-light"><%= link_to category.name, category_path(category) %> &nbsp;</span>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
    <%# Render the form partial for errors.  Pass in the @user object as the contextual variable to the partial %>
      <%= render 'shared/errors', obj: @category %>
      <%# Change form scope to show current information to be edited %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a Category Name" %>
          </div>
        </div>

        <div class="form-group-row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
  </div>
      <div class="mb-3">
      <%= link_to "[ Return to Articles listing ]", articles_path, class: "text-info" %>
    </div>
</div>

app/views/categories/edit.html.erb
<h1 class="mt-4">Edit Category Name</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="mt-4">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
<%#  loop through each article %>
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-danger" %></h5>
            <li><small><%= pluralize(category.articles.count, "article") %></small></li>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago,
            Edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="mt-4">Create a New Category</h1>

<%# If there were any errors with creating the user, display
to the end user in an unordered list %>

<%= render 'form' %>

app/views/categories/show.html.erb
<h1 class="mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="row justify-content-md-center">
        <p class="badge badge-light"><%= link_to "Edit Category Name", edit_category_path(@category) %> </p>
    </div>
<% end %>

<div class="flickr_pagination">
    <%= will_paginate @category_articles, :container => false %>
</div>
<%= render 'articles/article', obj: @category.articles %>
<%= button_to "Create new Article",new_article_path, method: :get %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @category_articles, :container => false %>
</div>