config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Create the home and about routes
  root 'pages#home'
  get 'about', to: 'pages#about'
  # create only the individual routes one by one
  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="footer py-4">
    <div class="container text-center">
      <p>Copyright &copy; Jordan Handy RubyBlog</p>
    </div>
  </footer>

app/views/layouts/_messages.html.erb
  <div class="container">
    <% flash.each do |name, msg|%>
    <div class="<%= flash_class(name) %>" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    </div>

app/views/layouts/_navigation.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "RUBYBLOG", root_path, class: "navbar-brand", id: "logo" %><img src="https://cdn.emojidex.com/emoji/seal/Ruby.png" alt="Ruby" width="25">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%# <a class="nav-link" href="#">HOME<span class="sr-only">(current)</span></a> %>
        <%= link_to "HOME", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "USERS", users_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          BLOG
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "Articles", articles_path, class: "dropdown-item" %>
          <% if logged_in? %>
            <%= link_to "Create Article", new_article_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          CATEGORIES
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "View Categories", categories_path, class: "dropdown-item" %>
          <% if logged_in? && current_user.admin? %>
            <%= link_to "Create Category", new_category_path, class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <li class="nav-item">
        <%# <a class="nav-link" href="#">ABOUT<span class="sr-only">(current)</span></a> %>
        <%= link_to "ABOUT", about_path, class: "nav-link"  %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <%= "(ADMIN)" if current_user.admin? %> PROFILE [<%= current_user.username %>]
          </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "View Your Profile", user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Edit Your Profile", edit_user_path(current_user), class: "dropdown-item" %>
          <%= link_to "Delete Your Profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, data: { confirm: "Are you sure?" } %>
        </div>
      </li>
        <li class="nav-item">
          <%= link_to "LOGOUT", logout_path, class: "nav-link", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "LOG IN", login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "SIGN UP", signup_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%# <a class="nav-link" href="#">MAIN SITE<span class="sr-only">(current)</span></a> %>
        <%= link_to "MAIN SITE", "https://www.jordanhandy.com", class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
  <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
  <%= render 'layouts/footer'%>
</html>